# Generated by Django 3.0.6 on 2020-05-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(blank=True, max_length=255, null=True)),
                ('mimg', models.CharField(blank=True, max_length=255, null=True)),
                ('mdesc', models.CharField(blank=True, max_length=4000, null=True)),
                ('mlink', models.CharField(blank=True, max_length=1100, null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
    ]
